### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by papazetis** [peterjohnhunt/wordpress-suite#7]
**Atom**: 1.14.1 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: [wordpress-suite](https://github.com/peterjohnhunt/wordpress-suite) package 0.4.5

### Stack Trace

Uncaught SyntaxError: Unexpected end of JSON input

```
At file:///C:/Users/papaz/AppData/Local/atom/app-1.14.1/resources/app.asar/static/index.html#%7B%22initialPaths%22%3A%5B%22C%3A%5C%5Cxampp%5C%5Chtdocs%5C%5Cwp%5C%5Cwp-content%5C%5Cplugins%5C%5Cuk-address-finder%22%5D%2C%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22C%3A%5C%5Cxampp%5C%5Chtdocs%5C%5Cwp%5C%5Cwp-content%5C%5Cplugins%5C%5Cuk-address-finder%22%2C%22initialLine%22%3Anull%2C%22initialColumn%22%3Anull%2C%22forceAddToWindow%22%3Afalse%7D%5D%2C%22windowInitializationScript%22%3A%22C%3A%5C%5CUsers%5C%5Cpapaz%5C%5CAppData%5C%5CLocal%5C%5Catom%5C%5Capp-1.14.1%5C%5Cresources%5C%5Capp.asar%5C%5Csrc%5C%5Cinitialize-application-window.js%22%2C%22resourcePath%22%3A%22C%3A%5C%5CUsers%5C%5Cpapaz%5C%5CAppData%5C%5CLocal%5C%5Catom%5C%5Capp-1.14.1%5C%5Cresources%5C%5Capp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22profileStartup%22%3Afalse%2C%22clearWindowState%22%3Afalse%2C%22env%22%3A%7B%22ALLUSERSPROFILE%22%3A%22C%3A%5C%5CProgramData%22%2C%22APPDATA%22%3A%22C%3A%5C%5CUsers%5C%5Cpapaz%5C%5CAppData%5C%5CRoaming%22%2C%22ATOM_HOME%22%3A%22C%3A%5C%5CUsers%5C%5Cpapaz%5C%5C.atom%22%2C%22CommonProgramFiles%22%3A%22C%3A%5C%5CProgram%20Files%20(x86)%5C%5CCommon%20Files%22%2C%22CommonProgramFiles(x86)%22%3A%22C%3A%5C%5CProgram%20Files%20(x86)%5C%5CCommon%20Files%22%2C%22CommonProgramW6432%22%3A%22C%3A%5C%5CProgram%20Files%5C%5CCommon%20Files%22%2C%22COMPUTERNAME%22%3A%22NICOLAS-PC%22%2C%22ComSpec%22%3A%22C%3A%5C%5CWINDOWS%5C%5Csystem32%5C%5Ccmd.exe%22%2C%22FPS_BROWSER_APP_PROFILE_STRING%22%3A%22Internet%20Explorer%22%2C%22FPS_BROWSER_USER_PROFILE_STRING%22%3A%22Default%22%2C%22GOOGLE_API_KEY%22%3A%22AIzaSyAQfxPJiounkhOjODEO5ZieffeBv6yft2Q%22%2C%22HOMEDRIVE%22%3A%22C%3A%22%2C%22HOMEPATH%22%3A%22%5C%5CUsers%5C%5Cpapaz%22%2C%22LOCALAPPDATA%22%3A%22C%3A%5C%5CUsers%5C%5Cpapaz%5C%5CAppData%5C%5CLocal%22%2C%22LOGONSERVER%22%3A%22%5C%5C%5C%5CNICOLAS-PC%22%2C%22NUMBER_OF_PROCESSORS%22%3A%224%22%2C%22OneDrive%22%3A%22C%3A%5C%5CUsers%5C%5Cpapaz%5C%5COneDrive%22%2C%22OS%22%3A%22Windows_NT%22%2C%22Path%22%3A%22C%3A%5C%5CWINDOWS%5C%5Csystem32%3BC%3A%5C%5CWINDOWS%3BC%3A%5C%5CWINDOWS%5C%5CSystem32%5C%5CWbem%3BC%3A%5C%5CWINDOWS%5C%5CSystem32%5C%5CWindowsPowerShell%5C%5Cv1.0%5C%5C%3BC%3A%5C%5CProgram%20Files%5C%5CTortoiseSVN%5C%5Cbin%3BC%3A%5C%5CUsers%5C%5Cpapaz%5C%5CAppData%5C%5CLocal%5C%5CMicrosoft%5C%5CWindowsApps%3BC%3A%5C%5CProgram%20Files%20(x86)%5C%5CBitvise%20SSH%20Client%3BC%3A%5C%5CUsers%5C%5Cpapaz%5C%5CAppData%5C%5CLocal%5C%5Catom%5C%5Cbin%3BC%3A%5C%5Cxampp%5C%5Cwpcs%5C%5Cvendor%5C%5Cbin%3BC%3A%5C%5Cxampp%5C%5Cphp%22%2C%22PATHEXT%22%3A%22.COM%3B.EXE%3B.BAT%3B.CMD%3B.VBS%3B.VBE%3B.JS%3B.JSE%3B.WSF%3B.WSH%3B.MSC%22%2C%22PROCESSOR_ARCHITECTURE%22%3A%22x86%22%2C%22PROCESSOR_ARCHITEW6432%22%3A%22AMD64%22%2C%22PROCESSOR_IDENTIFIER%22%3A%22Intel64%20Family%206%20Model%2058%20Stepping%209%2C%20GenuineIntel%22%2C%22PROCESSOR_LEVEL%22%3A%226%22%2C%22PROCESSOR_REVISION%22%3A%223a09%22%2C%22ProgramData%22%3A%22C%3A%5C%5CProgramData%22%2C%22ProgramFiles%22%3A%22C%3A%5C%5CProgram%20Files%20(x86)%22%2C%22ProgramFiles(x86)%22%3A%22C%3A%5C%5CProgram%20Files%20(x86)%22%2C%22ProgramW6432%22%3A%22C%3A%5C%5CProgram%20Files%22%2C%22PSModulePath%22%3A%22C%3A%5C%5CProgram%20Files%5C%5CWindowsPowerShell%5C%5CModules%3BC%3A%5C%5CWINDOWS%5C%5Csystem32%5C%5CWindowsPowerShell%5C%5Cv1.0%5C%5CModules%22%2C%22PUBLIC%22%3A%22C%3A%5C%5CUsers%5C%5CPublic%22%2C%22SESSIONNAME%22%3A%22Console%22%2C%22SystemDrive%22%3A%22C%3A%22%2C%22SystemRoot%22%3A%22C%3A%5C%5CWINDOWS%22%2C%22TEMP%22%3A%22C%3A%5C%5CUsers%5C%5Cpapaz%5C%5CAppData%5C%5CLocal%5C%5CTemp%22%2C%22TMP%22%3A%22C%3A%5C%5CUsers%5C%5Cpapaz%5C%5CAppData%5C%5CLocal%5C%5CTemp%22%2C%22USERDOMAIN%22%3A%22NICOLAS-PC%22%2C%22USERDOMAIN_ROAMINGPROFILE%22%3A%22NICOLAS-PC%22%2C%22USERNAME%22%3A%22papaz%22%2C%22USERPROFILE%22%3A%22C%3A%5C%5CUsers%5C%5Cpapaz%22%2C%22windir%22%3A%22C%3A%5C%5CWINDOWS%22%7D%2C%22appVersion%22%3A%221.14.1%22%2C%22atomHome%22%3A%22C%3A%5C%5CUsers%5C%5Cpapaz%5C%5C.atom%22%2C%22shellLoadTime%22%3A516%7D:1

SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at /packages/wordpress-suite/node_modules/wp-cli/lib/commands.js:13:19
    at ChildProcess.exithandler (child_process.js:225:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.29.17 
emmet 2.4.3 
wordpress-suite 0.4.5 
```

**Comment by peterjohnhunt** [comment]
Hi @papazetis! this is usually an issue related to wp cli on the local machine. Do you have wp cli installed locally, and does that work when running through command prompt?

**Comment by peterjohnhunt** [comment]
Hey @papazetis, closing this for now, but feel free to reopen with the follow up details!
